
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, NavBar } from "./_components";
import NavBar2 from "./_components/navbar/NavBar2";
import CookieBanner from "./_components/CookieBanner";

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: "Cilicosys",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NavBar2 />
      <body
        className={`${inter.variable} antialiased`}
      >
        <main>
          {children}
        </main>
        <CookieBanner />
      </body>
      <Footer />
    </html>
  );
}
