
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, NavBar } from "./_components";


const inter = Inter({ subsets: ['latin'] });


export const metadata = {
  title: "Cilicosys",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NavBar />
      <body
        className={`${inter.variable} antialiased`}
      >
        <main>
          {children}
        </main>
        
      </body>
      <Footer />
    </html>
  );
}
